mod naked_singles;
mod grid_steps;
mod locked_candidates_pairs;
mod locked_candidates_triples;
mod hidden_singles;
mod hidden_pairs;
mod hidden_triples;
mod naked_pairs;
// mod locked_candidates_pairs;
mod naked_triples;
mod thermo_steps;
mod thermo_candidates;
mod x_wing;
mod xy_wing;
mod common_peer_elimination;
mod puzzles;
